### ISSUE TITLE
com.facebook.react:react-native:0.42.3无法加载这个类库

### ISSUE THREAD

**Issue by yyclang** [liaoxd/asLockDemo#2]
我到官网上 https://bintray.com/bintray/jcenter/com.facebook.react:react-native/view 查看了一下这个类库，好像没有这个版本，楼主你工程环境能运行不

**Comment by yyclang** [comment]
换了版本发现，com.facebook.react.common.LifecycleState这个类库也找不到了，楼主方便解答一下这个问题吧

**Comment by kiplening** [comment]
那个是我之前加了ReactNative的一些界面    现在已经去掉了 。你把分支切换到pure分支上就能正常运行了。

**Comment by kiplening** [comment]
你再试试能不能用，如果可以的话  我就把这个issue关掉了哈

**Comment by yyclang** [comment]
能用，谢谢分享
